services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile

    env_file:
      - ./backend/.env 

  frontend:    
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile

    ports:
      - "80:80"   # Map port 80 of the container to port 80 on the host machine
      